#!/bin/bash

function sigint_handler {
    keep_running="no"
}

function print_usage {
    echo "Usage: $0 testbed/udcenter server/client [ip] [port]"
}

if [ $# -lt 2 ] || [ $# -gt 4 ]; then
    print_usage
    exit 1
fi

if [ "$1" != "udcenter" ] && [ "$1" != "testbed" ]; then
    print_usage
    exit 1
fi

if [ "$2" != "server" ] && [ "$2" != "client" ]; then
    print_usage
    exit 1
fi

args=""
if [ $# -gt 2 ]; then
    args="${args} $3"
fi
if [ $# -gt 3 ]; then
    args="${args} $4"
fi

if [ "$1" = "udcenter" ]; then
    grep_str="python udcenter.py"
    start_cmd=ud${2}_start${args}
else
    grep_str="python utest.py"
    start_cmd=tb${2}_start${args}
fi

trap sigint_handler INT
keep_running="yes"
while [ "${keep_running}" = "yes" ]; do
    pid=$(ps aux | grep "${grep_str}" | grep "${2}" | awk '{ print $2 }')
    if [ "${pid}" = "" ]; then
        ${start_cmd}
    fi
    sleep 120
done

