/*
 * Generated by MTK Easy PinMux Tool Version 1.0.4 for 7687. Copyright MediaTek Inc. (C) 2015.
 * Thu Jun 30 15:06:22 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/
#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H


#endif /* _EPT_EINT_DRV_H */


