#!/usr/bin/env bash

port=2000
if [ $# -gt 0 ];then
    port=$1
fi

cd ${HOME}/udcenter
PIDS=`ps aux | grep "python udcenter.py" | grep "controller" | grep "${port}" | awk '{ print $2 }'`
if [ "${PIDS}" != "" ]; then
    kill ${PIDS}
fi
rm -rf /tmp/.testbed_controller_${port}
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
screen -dmL python udcenter.py controller -p ${port}
